* [32m(HEAD detached at origin/wep_vla_v0.4.2_general_dataset_toolseg)[m
  main[m
  wep_vla_v0.3_feature_RGB[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/lrx[m
  [31mremotes/origin/lrx-integration[m
  [31mremotes/origin/main[m
  [31mremotes/origin/priorseg_policy[m
  [31mremotes/origin/priorseg_policy_temp[m
  [31mremotes/origin/priorseg_policy_temp_worldflow[m
  [31mremotes/origin/priorseg_policy_temp_worldflow_se3[m
  [31mremotes/origin/v0.0[m
  [31mremotes/origin/wep_vla_0.3_temp[m
  [31mremotes/origin/wep_vla_0.3_temp_0630[m
  [31mremotes/origin/wep_vla_0.3_temp_0712[m
  [31mremotes/origin/wep_vla_v0.0[m
  [31mremotes/origin/wep_vla_v0.1[m
  [31mremotes/origin/wep_vla_v0.2[m
  [31mremotes/origin/wep_vla_v0.2_new_priorseg[m
  [31mremotes/origin/wep_vla_v0.3[m
  [31mremotes/origin/wep_vla_v0.3.1[m
  [31mremotes/origin/wep_vla_v0.3.1_cache_v7[m
  [31mremotes/origin/wep_vla_v0.3.1_cache_v7_adapter[m
  [31mremotes/origin/wep_vla_v0.3.1_cache_v7_worldflow[m
  [31mremotes/origin/wep_vla_v0.3_action_fusion[m
  [31mremotes/origin/wep_vla_v0.3_action_fusion_self_attn[m
  [31mremotes/origin/wep_vla_v0.3_action_fusion_self_attn_no_voting_center[m
  [31mremotes/origin/wep_vla_v0.3_feature_RGB[m
  [31mremotes/origin/wep_vla_v0.3_min_max_topk[m
  [31mremotes/origin/wep_vla_v0.4[m
  [31mremotes/origin/wep_vla_v0.4.1[m
  [31mremotes/origin/wep_vla_v0.4.1_dataset_fixed[m
  [31mremotes/origin/wep_vla_v0.4.1_dataset_fixed_v1[m
  [31mremotes/origin/wep_vla_v0.4.1_dataset_fixed_v1.1[m
  [31mremotes/origin/wep_vla_v0.4.1_dataset_fixed_world_flow[m
  [31mremotes/origin/wep_vla_v0.4.2[m
  [31mremotes/origin/wep_vla_v0.4.2_general_dataset[m
  [31mremotes/origin/wep_vla_v0.4.2_general_dataset_multiview[m
  [31mremotes/origin/wep_vla_v0.4.2_general_dataset_toolseg[m
  [31mremotes/origin/wep_vla_v0.4_optimal_eval[m
  [31mremotes/origin/wep_vla_v0.5.0_auxiliary[m
  [31mremotes/origin/wep_vla_v0.5.0_double_flow[m
  [31mremotes/origin/wepvla_v03_adapter[m
